# Generated by Django 3.2.5 on 2021-07-12 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=264, null=True)),
                ('author', models.CharField(blank=True, max_length=264, null=True)),
                ('size', models.CharField(blank=True, max_length=264, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('album', models.CharField(blank=True, max_length=264, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('path', models.FileField(upload_to='music')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.ForeignKey(blank=True, max_length=264, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.music')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.ForeignKey(blank=True, choices=[('Pop', 'Pop'), ('Classic', 'Classic'), ('Romantic', 'Romantic'), ('Rock', 'Rock')], max_length=264, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.music')),
            ],
        ),
    ]
