# Generated by Django 3.2.5 on 2021-07-12 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='category_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musicapp.category'),
        ),
        migrations.AddField(
            model_name='music',
            name='singer_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musicapp.singer'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, choices=[('Pop', 'Pop'), ('Classic', 'Classic'), ('Romantic', 'Romantic'), ('Rock', 'Rock')], max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='singer_name',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
