# Generated by Django 3.2.5 on 2021-07-22 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicapp', '0005_comment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='music',
            name='singer_id',
        ),
        migrations.AddField(
            model_name='music',
            name='likes',
            field=models.ManyToManyField(related_name='music', to=settings.AUTH_USER_MODEL),
        ),
    ]
