# Generated by Django 3.2.5 on 2021-07-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_reply_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='user_reply',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
