# Generated by Django 3.2.5 on 2021-07-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_reply_user_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment_id',
        ),
    ]
