# Generated by Django 3.2.5 on 2021-07-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0009_remove_reply_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='comment_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musicapp.comment'),
            preserve_default=False,
        ),
    ]
