# Generated by Django 3.2.5 on 2021-07-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0010_reply_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment_id',
        ),
    ]
