# Generated by Django 3.2.5 on 2021-07-26 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0011_remove_reply_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='comment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.comment'),
        ),
    ]
