# Generated by Django 3.2.5 on 2021-07-27 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0013_alter_reply_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='musicapp.comment'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
